server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store?serverTimezone=Asia/Shanghai&useUnicode=ture&characterEnc
    username: root
    password: 288100
    oracleucp:
      user:
        address:
          max-count=20:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
#
#user.address.max-count=20
